spring:
  config:
    activate:
      on-profile: local
    import: optional:application-secret.properties
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_LOCAL}
    username: ${DB_USER_LOCAL}
    password: ${DB_PWD_LOCAL}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      ejb:
        naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

kakao:
  client-id: ${KAKAO_ID}
  authorization-grant-type: authorization_code
  redirect-uri: ${KAKAO_REDIRECT_LOCAL}

server:
  port: 8080