spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB


cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region: ap-northeast-2
    s3:
      bucket-name: ${BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
openai:
  api.key: ${API_KEY}

iamport:
  key: ${IAMPORT_KEY}
  secret: ${IAMPORT_SECRET}
